FROM node:20-alpine AS base
WORKDIR /app

FROM base AS deps
COPY package.json .
RUN npm install --production=false

FROM base AS build
COPY . .
RUN npm run build --silent

FROM node:20-alpine AS runner
WORKDIR /app
COPY --from=build /app/dist ./dist
CMD ["node", "dist/apps/api/main.js"]
